#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Manipulator
version:      0.04
version_from: Manipulator.pm
installdirs:  site
requires:
    HTML::Parser:                  3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
